[package]
authors = ["Jason Ozias <jason.ozias@kroger.com>"]
license = "MIT/Apache-2.0"
name = "aoc"
readme = "README.md"
version = "0.1.0"

[dependencies]
clap = "2.28.0"
error-chain = "0.11.0"
ndarray = "0.10.13"
regex = "0.2.3"
pathfinding = "0.6.8"
itertools = "0.7.4"
bytecount = "0.2.0"
primal = "0.2.3"
